### ISSUE TITLE
`Contract`-style interface (meta/combined issue)

### ISSUE THREAD

**Issue by ngua** [Plutonomicon/cardano-browser-tx#109]
This is a combined issue for designing and implementing a `Contract` interface that will allow library users to more easily port their Haskell code over. We can spin more issues off later, but this should serve as a broader overview of the work that needs to be done and/or any questions that might arise along the way

### Defining the `Contract` monad

Our `Contract` type can wrap the `QueryM` interface we've already defined (the latter should be opaque to users beyond supplying the required `QueryConfig`). The Plutus definition of `Contract` is similar to the following:

```haskell
newtype Contract (w :: Type) (s :: Row Type) (e :: Type) (a :: Type) = Contract { ... }
```

where

- `(w :: Type)` is usually some `Monoid` used in `Contract`'s `Writer`-like capabilities
- `(s :: Row Type)` (note this is the `Row` from the `row-types` package) represents the contract schema
- `(e :: Type)` represents the errors that the contract can throw

We'll need to add typeclass instances as necessary (e.g. `MonadError` or `MonadThrow`, `MonadTell`, etc...) to our `Contract`. Plutus' `Contract` uses free monads under the hood, so the underlying implementation will not be of much help to us with this part

### Auxiliary types and typeclasses

There are other types and typeclasses that we might need to re-implement, including:

- Something similar to [`AsContractError`](https://playground.plutus.iohkdev.io/doc/haddock/plutus-contract/html/Plutus-Contract.html#t:AsContractError)

### Essential contract actions

We shouldn't try to fully re-implement all `Contract` actions right away as there are quite a few of them. Instead, we should focus on the following essential `Contract` actions that are commonly encountered in off-chain Plutus code:

- [x] `utxosAt` - We can just wrap the `QueryM` action we've already defined for this
- [ ] [`waitNSlots`](https://playground.plutus.iohkdev.io/doc/haddock/plutus-contract/html/Plutus-Contract.html#v:waitNSlots) or a similar waiting capability
- [ ] [`{datum,validator,mintingPolicy}FromHash`](https://playground.plutus.iohkdev.io/doc/haddock/plutus-contract/html/Plutus-Contract.html#v:datumFromHash) - also see #30 
- [ ] [`txFromTxId`](https://playground.plutus.iohkdev.io/doc/haddock/plutus-contract/html/Plutus-Contract.html#v:txFromTxId) - also see #30
- [ ] [`ownPaymentPubKeyHash`](https://playground.plutus.iohkdev.io/doc/haddock/plutus-contract/html/Plutus-Contract.html#v:ownPaymentPubKeyHash) - Can convert from `getWalletAddress`
- [ ] [`awaitTxConfirmed`](https://playground.plutus.iohkdev.io/doc/haddock/plutus-contract/html/Plutus-Contract.html#v:awaitTxConfirmed)
- [ ] [`submitTxConstraints{With,...}`](https://playground.plutus.iohkdev.io/doc/haddock/plutus-contract/html/Plutus-Contract.html#v:submitTxConstraintsWith)

**NOTE**: If you think something is missing from the above list, please edit this issue or leave a comment below

**Comment by ngua** [comment]
We can just expose the `QueryM` interface directly
